# Generated by Django 5.0.1 on 2024-02-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='receipes',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='recipe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='recipe_name',
            new_name='receipe_name',
        ),
    ]
