# Generated by Django 5.0.1 on 2024-02-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegies', '0002_rename_recipe_receipes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receipes',
            new_name='receipe',
        ),
    ]
